# Generated by Django 4.0.1 on 2022-01-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('led_one_hex', models.CharField(max_length=10)),
                ('led_two_hex', models.CharField(max_length=10)),
                ('led_three_hex', models.CharField(max_length=10)),
                ('led_four_hex', models.CharField(max_length=10)),
            ],
        ),
    ]
