# Generated by Django 4.0.1 on 2022-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='complete_name',
            field=models.CharField(default='FightClub', max_length=100),
            preserve_default=False,
        ),
    ]
